### ISSUE TITLE
Implement signup page

### ISSUE THREAD

**Issue by yogesh-kansal** [Synergise-IIT-Bhubaneswar/Invoicia#1]
# Description
Signp page is page which will allow users to signup in the web app. This page basically contains a form which has fields for emailId, username and password.
# Checklist
- [ ] Want to do docuementation of any file
- [x] want to add files (js/css/other)
- [ ] Want to modify files (js/css/other)

**Comment by ritik3131** [comment]
Hey @yogesh-kansal I would like to work on this issue.

**Comment by yogesh-kansal** [comment]
okk, go ahead.
