### ISSUE TITLE
User API(server side functionality for user)

### ISSUE THREAD

**Issue by yogesh-kansal** [Synergise-IIT-Bhubaneswar/Invoicia#18]
# Description
- route to get user.
- route to update user information.
- route to get list of all users.

## Endpoints
- GET on '/user/userId/getUser'
- GET on 'user/allUsers'
- PATCH on '/user/userId/editPorfile'

## Files description 
routes will in '/routes' folder with file name 'userRouter.js'.
functionality of routes will be in '/controllers' folder with file name 'usercontroller.js'

# Checklist
- [x] want to add files (js/css/other)
- [x] Want to modify files (js/css/other)

**Comment by ritik3131** [comment]
@yogesh-kansal I would like implement this issue
