### ISSUE TITLE
Implement login page

### ISSUE THREAD

**Issue by yogesh-kansal** [Synergise-IIT-Bhubaneswar/Invoicia#2]
# Description of page
login page is page which will allow users to login for app. This page will contain a form which will be having fields for emailId and password for user.
# Checklist
- [x] want to add files (js/css/other)

**Comment by ritik3131** [comment]
Hey @yogesh-kansal I would like to work on this issue.

**Comment by yogesh-kansal** [comment]
okk, go ahead
