### ISSUE TITLE
Create feedback schema

### ISSUE THREAD

**Issue by yogesh-kansal** [Synergise-IIT-Bhubaneswar/Invoicia#24]
# Description
create database schema for feedbacks using mongoose library.

## schema description
```
{
      "_id":"feedbackId",
     "author": "userId",
     "feedback" "....", //min length 20
     "rating": 5  //max value 5

}

```
## file description
make changes in [this file](https://github.com/Synergise-IIT-Bhubaneswar/Invoicia/blob/master/invoicing_app/models/feedback.js).

# Checklist
- [x] want to add files (js/css/other)

**Comment by ritik3131** [comment]
@yogesh-kansal I would like to implement this issue
