### ISSUE TITLE
Implement header of wep app

### ISSUE THREAD

**Issue by yogesh-kansal** [Synergise-IIT-Bhubaneswar/Invoicia#3]
# Description
Header is a component of every page which will reside at the top of it. Bascially it will contain navigation for the app as well. 
- Left section of header contains name of the app.
- Right siection of header conatins navigation section for different pages.
- Navigation section has mainly 3 tabs `Home`,  `All Invoices`,  `Profile`.

# Checklist
- [x] want to add files (js/css/other)

**Comment by vishnu921** [comment]
I would like to work on this issue.

**Comment by yogesh-kansal** [comment]
okk, go ahead.
