### ISSUE TITLE
Implement footer for web app

### ISSUE THREAD

**Issue by yogesh-kansal** [Synergise-IIT-Bhubaneswar/Invoicia#4]
# Description
Footer is component of app which reside at the bottom of the page. Footer will contain links for platform such as facebook, instgam, twitter, github and linkedin in left panel and address and other links in right panel. As of now you can reference these links to dummy endpoints.

# Checklist
- [x] want to add files (js/css/other)
- [x] Want to modify files (js/css/other)

**Comment by vishnu921** [comment]
I would like to work on this issue.

**Comment by yogesh-kansal** [comment]
okk, go ahead and update checklist in issue description according to your work.
