### ISSUE TITLE
Implement user profile page

### ISSUE THREAD

**Issue by yogesh-kansal** [Synergise-IIT-Bhubaneswar/Invoicia#5]
# Description
User profile page is page which shows basic information of user.
- Show basic details of page such as Username, EmailId, Description and other details.
- Show profile pic of user (As of now you can put dummy image there). 
- Social media links of users.

# Checklist
- [x] want to add files (js/css/other)

**Comment by Shashwat545** [comment]
I would like to work on this issue @yogesh-kansal

**Comment by yogesh-kansal** [comment]
okk, go ahead.

**Comment by ritik3131** [comment]
Hey @yogesh-kansal I would like to work on this issue
